#!/bin/bash
#* Copyright (c) 2011  by HPC Links 
#* 
#* Permission to use, copy, modify, and distribute this software for any 
#* purpose with or without fee is hereby granted, provided that the above 
#* copyright notice and this permission notice appear in all copies. 
#* 
#* THE SOFTWARE IS PROVIDED "AS IS" AND HPC Links DISCLAIMS ALL WARRANTIES 
#* WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
#* MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL HPC Links BE LIABLE FOR 
#* ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
#* WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
#* ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT 
#* OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#* 
#*   HPC Links 
#*   B-8, Second Floor 
#*   May Fair Garden 
#*   New Delhi, India 110016

# ---------------------------------------------------------------------------------
#
#  openxrx: let everyone use xrx
#
#  Author: Greg Rodgers
#
# ---------------------------------------------------------------------------------

#  You need to run this after adding userids or booting nodes
#   

. /etc/sysconfig/vex

XCPUBIN="$VEXHOME/bin"

NODES=""
for i in `sed -e 's/,/ /g' $VEXVAR/etc/vex.conf ` ; do 
   NODES="$NODES `echo $i | cut -d: -f1 `"
done

NODES=${1:-$NODES}

NODES="127.0.0.1 $NODES"

echo "opening $NODES"

if [ "$VEXIDMETH" == "local" ] ; then
   for i in `cat /etc/passwd` ; do 
      USERNAM=`echo $i | cut -d: -f 1`
      HOMEDIR=`echo $i | cut -d: -f 6`
      if [ "$HOMEDIR" != "/root" ] ; then 
         USERNUM=`echo $i | cut -d: -f 3`
         GROUPNUM=`echo $i | cut -d: -f 4`
         PUBKEY="${HOMEDIR}/.ssh/id_rsa.pub"
         if [ -r $PUBKEY ] ; then 
            line2=`grep $GROUPNUM /etc/group`
            GROUPNAME=`echo $line2 | cut -d: -f 1`
            for QSYS in $NODES ; do 
               echo xgroupset add $QSYS $GROUPNAME $GROUPNUM
              $XCPUBIN/xgroupset add $QSYS $GROUPNAME $GROUPNUM
               echo xuserset add $QSYS $USERNAM $USERNUM $GROUPNAME $PUBKEY
              $XCPUBIN/xuserset add $QSYS $USERNAM $USERNUM $GROUPNAME $PUBKEY
            done
         fi
      fi
   done
elif [ "$VEXIDMETH" == "yp" ] ; then
   while IFS=: read -r USERNAME f2 USERID GROUPID f5 HOMEDIR f7
   do
      if [ "$HOMEDIR" != "/root" ] ; then
         PUBKEY="${HOMEDIR}/.ssh/id_rsa.pub"
         if [ -r $PUBKEY ] ; then 
            groupline=`ypcat group | grep ":$GROUPID:"`
            echo $groupline
            GROUPNAME=`echo $groupline | cut -d: -f 1`
            for QSYS in $NODES ; do 
               echo xgroupset add $QSYS $GROUPNAME $GROUPID
               $XCPUBIN/xgroupset add $QSYS $GROUPNAME $GROUPID
               echo xuserset add $QSYS $USERNAME $USERID $GROUPNAME $PUBKEY
               $XCPUBIN/xuserset add $QSYS $USERNAME $USERID $GROUPNAME $PUBKEY
            done
         fi   
      fi   
   done< <(ypcat passwd)
else
   echo "ID method \"$VEXIDMETH\" not supported"
   exit 1
fi


