#!/bin/bash
#* Copyright (c) 2011  by HPC Links 
#* 
#* Permission to use, copy, modify, and distribute this software for any 
#* purpose with or without fee is hereby granted, provided that the above 
#* copyright notice and this permission notice appear in all copies. 
#* 
#* THE SOFTWARE IS PROVIDED "AS IS" AND HPC Links DISCLAIMS ALL WARRANTIES 
#* WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
#* MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL HPC Links BE LIABLE FOR 
#* ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
#* WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
#* ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT 
#* OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#* 
#*   HPC Links 
#*   B-8, Second Floor 
#*   May Fair Garden 
#*   New Delhi, India 110016
# ---------------------------------------------------------------------------------
#
#  openxrx_node: Initialize a compute node after xcpufs on this compute
#								 node [re]starts up.
#								 This would typically happen when a compute node [re]boots
#								 or if the xcpufs is restarted on the compute node
#
#  Author: Greg Rodgers
#
# ---------------------------------------------------------------------------------

XCPUBIN="$VEXHOME/bin"

NODES=$1
echo "opening $NODES"

for i in `cat /etc/passwd` ; do 
   USERNAM=`echo $i | cut -d: -f 1`
   HOMEDIR=`echo $i | cut -d: -f 6`
   if [ "$HOMEDIR" != "/root" ] ; then 
      USERNUM=`echo $i | cut -d: -f 3`
      GROUPNUM=`echo $i | cut -d: -f 4`
      PUBKEY="${HOMEDIR}/.ssh/id_rsa.pub"
      if [ -r $PUBKEY ] ; then 
         line2=`grep $GROUPNUM /etc/group`
         GROUPNAME=`echo $line2 | cut -d: -f 1`
         for QSYS in $NODES ; do 
            echo xgroupset add $QSYS $GROUPNAME $GROUPNUM
           $XCPUBIN/xgroupset add $QSYS $GROUPNAME $GROUPNUM
            echo xuserset add $QSYS $USERNAM $USERNUM $GROUPNAME $PUBKEY
           $XCPUBIN/xuserset add $QSYS $USERNAM $USERNUM $GROUPNAME $PUBKEY
         done
      fi
   fi
done
